version: '2'

services:

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/blog.conf:/etc/nginx/sites-enabled/blog.conf
      - /etc/letsencrypt/live/blogciso.com/privkey.pem:/etc/nginx/blogciso.com/privkey.pem
      - /etc/letsencrypt/live/blogciso.com/fullchain.pem:/etc/nginx/blogciso.com/fullchain.pem
    ports:
      - "80:80"
      - "443:443"
    links:
      - ghost
    restart: always

  ghost:
    build: ./ghost
    volumes:
      - ghost:/var/lib/ghost
    #ports: 
    #  - "2368:2368"
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  ghost:
